
services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app           # Mount project folder
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
